"""
Sales Data Analysis Package
---------------------------
Modular package for sales data processing, metrics analysis, top performer tracking,
and data visualizations.
"""

from .data_loader import load_dataset, inspect_data, print_data_inspection
from .sales_analysis import (
    get_total_sales,
    get_product_sales,
    get_city_sales,
    get_region_sales,
    get_monthly_sales,
    get_payment_sales,
    get_category_sales,
    get_sales_summary,
    print_sales_report,
)
from .profit_analysis import (
    get_total_profit,
    get_product_profit,
    get_city_profit,
    get_region_profit,
    get_monthly_profit,
    get_payment_profit,
    get_category_profit,
    get_overall_profit_margin,
    get_product_avg_profit,
    get_discount_avg_profit,
    print_profit_report,
)
from .quantity_analysis import (
    get_total_quantity,
    get_product_quantity,
    get_category_quantity,
    get_city_quantity,
    get_region_quantity,
    get_payment_quantity,
    get_discount_stats,
    get_product_avg_discount,
    print_quantity_discount_report,
)
from .top_performers import (
    get_top_products_by_sales,
    get_top_products_by_profit,
    get_top_products_by_quantity,
    get_top_cities_by_sales,
    get_top_cities_by_profit,
    get_best_sales_month,
    get_best_profit_month,
    get_best_sales_region,
    get_best_profit_region,
    get_best_payment_method,
    generate_insights_and_conclusion,
    print_top_performers_report,
)
from .visualization import (
    plot_bar_chart,
    plot_dual_bar_chart,
    plot_scatter_chart,
    plot_all_visualizations,
)

__all__ = [
    "load_dataset",
    "inspect_data",
    "print_data_inspection",
    "get_total_sales",
    "get_product_sales",
    "get_city_sales",
    "get_region_sales",
    "get_monthly_sales",
    "get_payment_sales",
    "get_category_sales",
    "get_sales_summary",
    "print_sales_report",
    "get_total_profit",
    "get_product_profit",
    "get_city_profit",
    "get_region_profit",
    "get_monthly_profit",
    "get_payment_profit",
    "get_category_profit",
    "get_overall_profit_margin",
    "get_product_avg_profit",
    "get_discount_avg_profit",
    "print_profit_report",
    "get_total_quantity",
    "get_product_quantity",
    "get_category_quantity",
    "get_city_quantity",
    "get_region_quantity",
    "get_payment_quantity",
    "get_discount_stats",
    "get_product_avg_discount",
    "print_quantity_discount_report",
    "get_top_products_by_sales",
    "get_top_products_by_profit",
    "get_top_products_by_quantity",
    "get_top_cities_by_sales",
    "get_top_cities_by_profit",
    "get_best_sales_month",
    "get_best_profit_month",
    "get_best_sales_region",
    "get_best_profit_region",
    "get_best_payment_method",
    "generate_insights_and_conclusion",
    "print_top_performers_report",
    "plot_bar_chart",
    "plot_dual_bar_chart",
    "plot_scatter_chart",
    "plot_all_visualizations",
]
